[phases.setup]
nixPkgs = [
  'postgresql',
  'vips'
]

[phases.setup.nodejs]
version = "18.19.0"
nodeEnv = "production"

# Set the working directory
workdir = "/app"

# Simple copy phase - copy everything
[phases.copy]
path = "."

[phases.install]
cmds = [
  'cd /app',
  'npm config set legacy-peer-deps true',
  'npm install --omit=dev',
  'bundle config set --local path "vendor/bundle"',
  'bundle install --deployment --without development test'
]

[phases.build]
cmds = [
  'cd /app',
  'npm run build',
  'RAILS_ENV=production bundle exec rails assets:precompile'
]

[start]
cmd = 'bundle exec rails server -p ${PORT:-3000} -e production'

[variables]
NODE_ENV = "production"
RAILS_ENV = "production"