[phases.setup]
nixPkgs = [
  'postgresql',
  'vips'
]

[phases.setup.nodejs]
version = "18.19.0"
nodeEnv = "production"

# Define the working directory
[phases.setup.working_dir]
path = "/app"

# Copy necessary files
[phases.copy]
paths = [
  ["package.json", "/app/package.json"],
  ["package-lock.json", "/app/package-lock.json"],
  ["Gemfile", "/app/Gemfile"],
  ["Gemfile.lock", "/app/Gemfile.lock"],
  [".", "/app"]
]

[phases.install]
cmds = [
  # Ensure we're in the correct directory
  'cd /app',
  # Set npm config
  'npm config set legacy-peer-deps true',
  # Install production dependencies
  'npm install --omit=dev',
  # Install Ruby dependencies
  'bundle config set --local path "vendor/bundle"',
  'bundle install --deployment --without development test'
]

[phases.build]
cmds = [
  'cd /app',
  # Build assets
  'npm run build',
  'bundle exec rails assets:precompile RAILS_ENV=production'
]

[start]
cmd = 'cd /app && bundle exec rails server -p ${PORT:-3000} -e production'

[variables]
NODE_ENV = "production"
RAILS_ENV = "production"