[phases.setup]
nixPkgs = [
  'postgresql',
  'vips'
]

[phases.setup.nodejs]
version = "18.19.0"
nodeEnv = "production"

[phases.setup.before]
cmds = [
  'mkdir -p /app',
  'cp -r . /app/',
  'cd /app',
  # Debug output
  'echo "Current directory: $(pwd)"',
  'echo "Contents of /app:"',
  'ls -la /app'
]

[phases.install]
cmds = [
  # Ensure correct directory
  'cd /app || exit 1',
  # Debug output
  'pwd',
  'ls -la',
  # Install dependencies
  'npm config set legacy-peer-deps true',
  'npm install --omit=dev',
  'bundle config set --local path "vendor/bundle"',
  'bundle install --deployment --without development test'
]

[phases.build]
cmds = [
  'cd /app',
  'npm run build',
  'RAILS_ENV=production bundle exec rails assets:precompile'
]

[start]
cmd = 'cd /app && bundle exec rails server -p ${PORT:-3000} -e production'

[variables]
NODE_ENV = "production"
RAILS_ENV = "production"