[phases.setup]
nixPkgs = [
  'postgresql',
  'vips'
]

[phases.setup.nodejs]
version = "18.19.0"
nodeEnv = "production"

# Copy all files to the build directory
[phases.copy]
path = "."
include = [
  "package.json",
  "package-lock.json",
  "Gemfile",
  "Gemfile.lock",
  "app",
  "config",
  "public",
  "bin",
  "lib",
  "db",
  "vendor"
]

[phases.install]
cmds = [
  # Set npm config
  'npm config set legacy-peer-deps true',
  # Install production dependencies
  'npm install --omit=dev',
  # Install Ruby dependencies
  'bundle config set --local path "vendor/bundle"',
  'bundle install --deployment --without development test'
]

[phases.build]
cmds = [
  # Build assets
  'npm run build',
  'bundle exec rails assets:precompile RAILS_ENV=production'
]

[start]
cmd = 'bundle exec rails server -p ${PORT:-3000} -e production'

[variables]
NODE_ENV = "production"
RAILS_ENV = "production"