[phases.setup]
nixPkgs = [
  'postgresql',
  'vips'
]

[phases.setup.nodejs]
provider = "nodejs-slim"
version = "18.19.0"
installMethod = "standalone"

[phases.install]
cmds = [
  # Remove any existing Node.js installations
  'rm -rf /usr/local/bin/node /usr/local/bin/npm',
  # Install dependencies
  'npm config set legacy-peer-deps true',
  'bundle install --deployment --without development test',
  'npm ci --production'
]

[phases.build]
cmds = [
  'NODE_ENV=production npm run build',
  'RAILS_ENV=production bundle exec rails assets:precompile'
]

[start]
cmd = 'bundle exec rails server -p ${PORT:-3000} -e production'

[variables]
NODE_VERSION = "18.19.0"