[phases.setup]
nixPkgs = [
  'postgresql',
  'vips'
]

[phases.setup.nodejs]
version = "18.19.0"
nodeEnv = "production"

[phases.install]
cmds = [
  # NPM setup
  'npm config set legacy-peer-deps true',
  # Use regular npm install instead of npm ci for more flexibility
  'npm install --production',
  # Bundle install for Ruby dependencies
  'bundle install --deployment --without development test',
  # Run Vite upgrade
  'bundle exec vite upgrade'
]

[phases.build]
cmds = [
  # Clear any existing builds
  'rm -rf public/assets public/vite',
  # Setup Vite
  'bundle exec vite install',
  # Build assets
  'RAILS_ENV=production bundle exec vite build',
  'RAILS_ENV=production bundle exec rails assets:precompile'
]

[start]
cmd = 'bundle exec rails server -p ${PORT:-3000} -e production'

[variables]
NODE_ENV = "production"
RAILS_ENV = "production"