[build]
builder = "nixpacks"
buildCommand = "bundle install && bundle exec rake assets:precompile"

[deploy]
startCommand = "bundle exec rails server"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[database]
type = "postgres"